import type { Metadata } from "next";
import "../globals.css";
import ThemeProvider from "@/components/custom/ThemeProvider";
import LayoutSection from "@/components/custom/LayoutSection";
import { Toaster } from "@/components/ui/toaster";
import { ClientProvider } from "@/api";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2991915240600971"
          crossOrigin="anonymous"
        />

        <ClientProvider>
          <ReactQueryDevtools initialIsOpen={false} />

          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster />
            <LayoutSection>{children}</LayoutSection>
          </ThemeProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
